echo "Hello world"
echo "updated test from git bash"
echo "updated from git bash using featureA branch"
echo "updated from featureB"
echo "update from local repo merge concept"
echo "updated from remote repo merge concept"
echo "added comment after v1 tag added"
